@startuml

actor User
participant AuthController
participant AuthService
participant UserRepository
participant JwtProvider
participant PasswordEncoder
participant GlobalExceptionHandler
participant ApiResponseDto

database DB

== login == 

User -> AuthController : POST api/auth/login login(AuthRequestDto)
AuthController -> AuthService : authenticate(AuthRequestDto)

AuthService -> UserRepository : findByEmail(email)
UserRepository -> DB : SELECT * FROM users WHERE email=?

alt user not found
  DB --> UserRepository : null
  UserRepository --> AuthService : null
  AuthService --> GlobalExceptionHandler : throw AuthenticationException
  GlobalExceptionHandler --> User : 401 "ERROR" ApiResponseDto<String> "メールアドレスまたはパスワードが正しくありません。。"
    
else OK
  DB --> UserRepository : user data
  UserRepository --> AuthService :user
  AuthService -> User : getStatus()
  alt status is deleted
    User --> AuthService : Status.DELETED
    AuthService --> GlobalExceptionHandler : throw AuthenticationException
    GlobalExceptionHandler --> User : 401 "ERROR" ApiResponseDto<String> "メールアドレスまたはパスワードが正しくありません。"
  
  else OK
    User --> AuthService : true
    AuthService -> User : getPassword()
  AuthService -> PasswordEncoder : matches(req.password, user.password)

  alt password does not match
    PasswordEncoder --> AuthService : false
    AuthService --> GlobalExceptionHandler : throw AuthenticationException
    GlobalExceptionHandler --> User : 401 "ERROR" ApiResponseDto<String> "メールアドレスまたはパスワードが正しくありません。"

  else OK
    AuthService -> JwtProvider : genetateToken(id)
    JwtProvider --> AuthService : token
    AuthService --> AuthController : token
    AuthController --> User : 200 "SUCCESS" + ApiResponseDto<String> 
  end
end

== logout ==
User -> Frontend : logout click
Frontend -> Frontend : remove JWT
Frontend --> User : logout success

@enduml